version: 0.2

env:
  variables:
    DISTRO: "ubuntu"
    IMAGE_VERSION: "focal"
    IMAGE_VARIANT: "20240530"
    POSTGRES_MAJOR_VERSION: "13"
    POSTGIS_MAJOR: "3.4"

phases:
  install:
    runtime-versions:
      docker: 23
  pre_build:
    commands:
      - |
        echo '## Example environment file for docker-compose and builders
        COMPOSE_PROJECT_NAME=postgis
        ## For build arguments
        DISTRO=ubuntu
        IMAGE_VERSION=focal
        IMAGE_VARIANT=20240530
        # Set GENERATE_ALL_LOCALE to empty value or 0 to build just default LOCALE: en_US.UTF-8
        GENERATE_ALL_LOCALE=0
        # Set the language if you need to specify LANG locale at build time
        LANG=en_US.UTF-8
        # locale filter to include in the locale generator
        LANGS="en_US.UTF-8,id_ID.UTF-8"
        POSTGRES_MAJOR_VERSION=13
        POSTGIS_MAJOR_VERSION=3
        POSTGIS_MINOR_RELEASE=4
        TAG=447900098106.dkr.ecr.$AWS_REGION.amazonaws.com/postgis:$POSTGRES_MAJOR_VERSION-$POSTGIS_MAJOR
        BUILD_TIMESCALE=false
        TIMESCALE_VERSION=2-2.14.2' > .env
  build:
    commands:
      - ./build.sh
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker tag kartoza/postgis:$POSTGRES_MAJOR_VERSION-$POSTGIS_MAJOR 447900098106.dkr.ecr.$AWS_REGION.amazonaws.com/postgis:$POSTGRES_MAJOR_VERSION-$POSTGIS_MAJOR
      - docker push 447900098106.dkr.ecr.$AWS_REGION.amazonaws.com/postgis:$POSTGRES_MAJOR_VERSION-$POSTGIS_MAJOR